package com.lonbon.cloud.user.domain.dto.user;


import com.lonbon.cloud.user.domain.entity.User;
import io.github.linpeilie.annotations.AutoMapper;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

import java.util.UUID;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.User }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@AutoMapper(target = User.class, reverseConvertGenerate = false)
@Data
public class CreateDTO {


    /**
     * 用户名
     * 对应lb_location_care.lb_account.username
     */
    @NotEmpty
    private String username;
    /**
     * 密码哈希
     * 对应lb_location_care.lb_account.password
     */
    @NotEmpty
    private String passwordHash;
    /**
     * 当前租户ID，一个用户可以关联多个租户，currentTenantId表示当前登录的租户ID
     */
    private UUID currentTenantId;
    /**
     * 是否超级管理员
     */
    private Boolean isSuperAdmin;


}
