package com.lonbon.cloud.user.domain.dto;


import com.lonbon.cloud.user.domain.entity.StaffAttribute;
import com.lonbon.cloud.user.domain.entity.TenantAttribute;
import io.github.linpeilie.annotations.AutoMapper;
import io.github.linpeilie.annotations.AutoMappers;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

import java.util.UUID;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.TenantAttribute }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: normal
 */
@Data
@AutoMappers({@AutoMapper(target = TenantAttribute.class, reverseConvertGenerate = false), @AutoMapper(target =
        StaffAttribute.class, reverseConvertGenerate = false)})
public class AttributeCreateDTO {

    private UUID id;

    @NotEmpty
    private String key;

    @NotEmpty
    private String value;
}
