package com.lonbon.cloud.user.domain.dto;


import lombok.Data;
import org.springdoc.core.annotations.ParameterObject;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.Tenant }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@ParameterObject
@Data
public class TenantQueryDTO {


    private String name;
    private String description;
    private String domain;


}
