package com.lonbon.cloud.user.domain.dto;


import com.lonbon.cloud.user.domain.entity.Tenant;
import io.github.linpeilie.annotations.AutoMapper;
import lombok.Data;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.Tenant }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@AutoMapper(target = Tenant.class)
@Data
public class TenantUpdateDTO {


    private String name;
    private String description;
    private String domain;


}
