package com.lonbon.cloud.user.domain.dto;


import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.lonbon.cloud.base.entity.BaseEntity;
import lombok.Data;
import com.lonbon.cloud.base.service.AttributeEntity;
import lombok.EqualsAndHashCode;
import org.jspecify.annotations.NonNull;

import java.util.UUID;

import lombok.AllArgsConstructor;
import org.jspecify.annotations.NullUnmarked;
import lombok.NoArgsConstructor;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.TenantAttribute }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: normal
 */
@Data
public class TenantAttributeCreateDTO {


    private @NonNull String key;
    private @NonNull String value;


}
