package com.lonbon.cloud.user.domain.dto;


import com.easy.query.core.annotation.EasyWhereCondition;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import org.springdoc.core.annotations.ParameterObject;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.lonbon.cloud.user.domain.entity.Tenant }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@ParameterObject
@Data
public class TenantQueryDTO {

    @EasyWhereCondition(type = EasyWhereCondition.Condition.EQUAL)
    @Schema(description = "名称，精确查询")
    private String name;

    @Schema(description = "名称，模糊查询")
    @EasyWhereCondition(propName = "name", type = EasyWhereCondition.Condition.LIKE)
    private String nameLike;

    private String description;


}
